"""Initial migration

Revision ID: 6dd52e6a915d
Revises: 
Create Date: 2025-02-03 12:11:56.759500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd52e6a915d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_agree', sa.Boolean(), nullable=False),
    sa.Column('question_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_fk'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('question_fk', sa.Integer(), nullable=False),
    sa.Column('agree_count', sa.Integer(), nullable=False),
    sa.Column('disagree_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_fk'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_fk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('response')
    op.drop_table('question')
    # ### end Alembic commands ###
